name: limeapi
services:
  server:
    build: .
    environment:
      - API_PORT=8080
      - PG_DBNAME=postgres
      - PG_HOST=db
      - DB_CONNECTION_URL=postgres://admin:1234@db:5432/postgres
      - ETH_NODE_URL=your_eth_node_url
      - JWT_SECRET=your_jwt_secret
    networks:
      - server-side
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    networks:
      - server-side
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  server-side: {}

volumes:
  db-data: {}
